<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('products')->insertOrIgnore([
            [
                'product_category_id' => 1,
                'name' => '5.5KVA Inverter',
                'price' => 1500000,
                'description' => 'Old Batch',
                'type' => '5.5kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter5_5.png',
            ], 
            [
                'product_category_id' => 1,
                'name' => '5.5KVA Inverter',
                'price' => 1500000,
                'description' => 'New Batch',
                'type' => '5.5kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter5_5.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '5KVA Inverter',
                'price' => 1000000,
                'description' => 'HHS',
                'type' => '5kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter5.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '6KVA Inverter',
                'price' => 1800000,
                'description' => '6KVA Inverter',
                'type' => '6kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter6.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '10KVA Inverter',
                'price' => 2500000,
                'description' => '10KVA Inverter',
                'type' => '10kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter10.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '2KVA Inverter',
                'price' => 1000000,
                'description' => '2KVA Inverter',
                'type' => '2kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter2.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '1.4KVA Inverter',
                'price' => 800000,
                'description' => '1.4KVA Inverter',
                'type' => '1.4kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter1_4.png',
            ],
            [
                'product_category_id' => 1,
                'name' => '3KVA Inverter',
                'price' => 1100000,
                'description' => '3KVA Inverter',
                'type' => '3kva',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/inverter3.png',
            ],
            [
                'product_category_id' => 2,
                'name' => '450 Watts Panel',
                'price' => 900000,
                'description' => '450 Watts Panel',
                'type' => '450 Watts Panel',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/panel450.png',
            ],
            [
                'product_category_id' => 2,
                'name' => '280 Watts Panel',
                'price' => 800000,
                'description' => '280 Watts Panel',
                'type' => '280 Watts Panel',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/panel280.png',
            ],
            [
                'product_category_id' => 2,
                'name' => '310 Watts Panel',
                'price' => 900000,
                'description' => '310 Watts Panel',
                'type' => '310 Watts Panel',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/panel310.png',
            ],
            [
                'product_category_id' => 2,
                'name' => '380 Watts Panel',
                'price' => 90000,
                'description' => '380 Watts Panel',
                'type' => '380 Watts Panel',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/panel380.png',
            ],
            [
                'product_category_id' => 3,
                'name' => 'Infrared Thermometer',
                'price' => 70000,
                'description' => 'Infrared Thermometer',
                'type' => 'Infrared Thermometer',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/rtmd.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTC-240',
                'price' => 2000000,
                'description' => 'New Batch',
                'type' => 'HTC-240',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htc_240.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTC-240',
                'price' => 1800000,
                'description' => 'Old Batch',
                'type' => 'HTC-240',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htc_240.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTC-112',
                'price' => 2000000,
                'description' => 'HTC-112',
                'type' => 'HTC-112',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htc_112.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTC-110',
                'price' => 2500000,
                'description' => 'HTC-110',
                'type' => 'HTC-110',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htc_110.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTCD-90',
                'price' => 2100000,
                'description' => 'HTCD-90',
                'type' => 'HTCD-90',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htcd_90.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HBC-150',
                'price' => 1200000,
                'description' => 'HBC-150',
                'type' => 'HBC-150',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/hbc_150.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HBC-240',
                'price' => 1800000,
                'description' => 'HBC-240',
                'type' => 'HBC-240',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/hbc_240.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HBC-286',
                'price' => 1400000,
                'description' => 'HBC-286',
                'type' => 'HBC-286',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/hbc_286.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HBC-260',
                'price' => 1300000,
                'description' => 'HBC-260',
                'type' => 'HBC-260',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/hbc_260.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'HTCD-160',
                'price' => 1400000,
                'description' => 'HTCD-160',
                'type' => 'HTCD-160',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/htcd_160.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'VACCINE BOXES',
                'price' => 1600000,
                'description' => 'VACCINE BOXES',
                'type' => 'VACCINE BOXES',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/vaccine_boxes.png',
            ],
            [
                'product_category_id' => 4,
                'name' => 'VACCINE CARRIERS',
                'price' => 1700000,
                'description' => 'VACCINE CARRIERS',
                'type' => 'VACCINE CARRIERS',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/vaccine_carriers.png',
            ],
            [
                'product_category_id' => 5,
                'name' => 'MDF728',
                'price' => 1900000,
                'description' => 'MDF728',
                'type' => 'MDF728',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/mdf728.png',
            ],
            [
                'product_category_id' => 5,
                'name' => 'DW-86L728D',
                'price' => 1100000,
                'description' => 'DW-86L728D',
                'type' => 'DW-86L728D',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/dw_86l728d.png',
            ],
            [
                'product_category_id' => 5,
                'name' => 'DW-86L628E',
                'price' => 1400000,
                'description' => 'DW-86L628E',
                'type' => 'DW-86L628E',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/dw_86l628e.png',
            ],
            [
                'product_category_id' => 6,
                'name' => 'Safety Boxes',
                'price' => 34000,
                'description' => 'Safety Boxes',
                'type' => 'Safety Boxes',
                'model' => '0000',
                'serial_number' => '0000',
                'featured_image' => config('app.url').'products/safety_boxes.png',
            ]
        ]);
    }
}
