<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('project_reports')->insertOrIgnore([

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ANIOCHA NORTH",
                "location" => "Onicha-Uku",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ANIOCHA NORTH",
                "location" => "Idumeji-Unor",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ANIOCHA SOUTH",
                "location" => "Ogwashi",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ANIOCHA SOUTH",
                "location" => "Adonte",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],


            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ANIOCHA SOUTH",
                "location" => "Ewulu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "BOMADI",
                "location" => "Ogriagbene",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "BOMADI",
                "location" => "Ego-Eze",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "BOMADI",
                "location" => "Akugbene",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "BURUTU",
                "location" => "Oboro",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "BURUTU",
                "location" => "Bikorogha",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ETHIOPE EAST",
                "location" => "Kokori",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ETHIOPE EAST",
                "location" => "Isiokolo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],



            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ETHIOPE EAST",
                "location" => "Ovu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ETHIOPE WEST",
                "location" => "Boboruku",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ETHIOPE WEST",
                "location" => "Ejemuoyenavwe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA NORTH/EAST",
                "location" => "Owa-Oyibu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA NORTH/EAST",
                "location" => "Ute-Ugbeje",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA NORTH/EAST",
                "location" => "Igbodo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA SOUTH",
                "location" => "Alisime",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA SOUTH",
                "location" => "Owuwu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "IKA SOUTH",
                "location" => "Agbor-Obi",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO NORTH",
                "location" => "Oyede",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO NORTH",
                "location" => "Ozoro 3",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],



            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO NORTH",
                "location" => "Uruotor",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO SOUTH",
                "location" => "Olomoro",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO SOUTH",
                "location" => "Ure",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "ISOKO SOUTH",
                "location" => "Enwhe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "NDOKWA EAST",
                "location" => "Aboh",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "NDOKWA EAST",
                "location" => "Ashaka",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "NDOKWA WEST",
                "location" => "Ogbe-Ogume",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],


            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "NDOKWA WEST",
                "location" => "FSP Kwale",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "NDOKWA WEST",
                "location" => "Utagba-Uno",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OKPE",
                "location" => "Adagbrassa",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OKPE",
                "location" => "Orerokpe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OKPE",
                "location" => "Egborode",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI NORTH",
                "location" => "Okoponta",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI NORTH",
                "location" => "Ogboli",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI NORTH",
                "location" => "Akwukwu-Igbo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI SOUTH",
                "location" => "Cable",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI SOUTH",
                "location" => "Umuonaje",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "OSHIMILI SOUTH",
                "location" => "Umuagu",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "PATANI",
                "location" => "Patani 2",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "PATANI",
                "location" => "Bulu-Angiama",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "PATANI",
                "location" => "Uduophori",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "SAPELE",
                "location" => "Urban",
                "delivery_status" => "delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "SAPELE",
                "location" => "Amukpe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "SAPELE",
                "location" => "Gana",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UDU",
                "location" => "Aladja",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UDU",
                "location" => "Orhovworun",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UDU",
                "location" => "Opete",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI NORTH",
                "location" => "Ekiugbo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI NORTH",
                "location" => "Evwreni",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI NORTH",
                "location" => "Ufuoma",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI SOUTH",
                "location" => "Okparabe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI SOUTH",
                "location" => "Ovwodokpokpo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UGHELLI SOUTH",
                "location" => "Otowodo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UKWANI",
                "location" => "Owa-Abbi",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UKWANI",
                "location" => "Umuaja",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UKWANI",
                "location" => "Umutu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UVWIE",
                "location" => "Ugborikoko",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UVWIE",
                "location" => "Ugbolokposo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "UVWIE",
                "location" => "Alaka",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI NORTH",
                "location" => "Abe-Ugborodo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI NORTH",
                "location" => "Ajagbodudu",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH",
                "location" => "Omadino",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH",
                "location" => "Ugbuwangwe",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],
            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH",
                "location" => "Orugbo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH WEST",
                "location" => "Ajudaibo",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH WEST",
                "location" => "Ogbe-Ijoh",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

            [
                "project_id" => "2",
                "state" => "DELTA STATE",
                "lga" => "WARRI SOUTH WEST",
                "location" => "Isaba",
                "delivery_status" => "not delivered",
                "installation_status" => "not installed",
                "rep" => "Sunny",
                "details" => "Sunny",
                "percent_completion" => "0",
            ],

        ]);

    }
}
